- name: Install Pipx
  ansible.builtin.apt:
    pkg:
    - pipx
  become: yes

- include_tasks: common/pipx/main.yml

# Obsolete
# - name: Install Python MySQL Library
#   ansible.builtin.apt:
#     pkg:
#     - python3-mysqldb
#     - python3-mysql.connector
#   become: yes
